
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-morpheus-client-db
  labels:
    app: agent-morpheus-client-db
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: agent-morpheus-client-db
  template:
    metadata:
      labels:
        app: agent-morpheus-client-db
    spec:
      containers:
        - name: mongodb
          image: docker.io/library/mongo:7.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: db
              protocol: TCP
              containerPort: 27017
          volumeMounts:
            - name: data
              mountPath: /data/db
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: agent-morpheus-client-data
---
apiVersion: v1
kind: Service
metadata:
  name: agent-morpheus-client-db
  labels:
    app: agent-morpheus-client-db
spec:
  ports:
  - name: db
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: agent-morpheus-client-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-morpheus-client
  labels:
    app: agent-morpheus-client
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: agent-morpheus-client
  template:
    metadata:
      labels:
        app: agent-morpheus-client
    spec:
      containers:
        - name: agent-morpheus-client
          image: quay.io/ecosystem-appeng/agent-morpheus-client:latest
          imagePullPolicy: Always
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
          env:
            - name: QUARKUS_REST-CLIENT_MORPHEUS_URL
              value: http://agent-morpheus-rh:8080/scan
            - name: QUARKUS_MONGODB_HOSTS
              value: agent-morpheus-client-db:27017
            - name: QUARKUS_MONGODB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: agent-morpheus-client-secret
                  key: mongodb.dbname
            - name: DOCKER_CONFIG
              value: /tmp/.docker
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-pat
                  key: GITHUB_TOKEN
          volumeMounts:
            - name: docker-config
              readOnly: true
              mountPath: /tmp/.docker
      volumes:
        - name: docker-config
          secret:
            secretName: image-registry-credentials
            items:
              - key: .dockerconfigjson
                path: config.json
            defaultMode: 420
---
apiVersion: v1
kind: Service
metadata:
  name: agent-morpheus-client
  labels:
    app: agent-morpheus-client
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: agent-morpheus-client
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: agent-morpheus-client
spec:
  port:
    targetPort: 8080 
  to:
    kind: Service
    name: agent-morpheus-client
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-morpheus-client-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
